### ISSUE TITLE
2nd Fire button Bug

### ISSUE THREAD

**Issue by AmitenTV** [AmiDARK/APU-SpecialFX-Extension-Releases#1] opened 2022-05-26 12:27 UTC
Hi ; Frederic I try the specialFX extension for 2nd Fire button and this is what I get ,

example
do
F=Fire(1,2)
Print F
loop

the result are 
0 value when run the example and when I press 2nd button the value change to -1 and when I release the 2nd button the value
dont change from -1 , dont change back to 0 as expected. seems like we keep pressing 2nd where its not...

Thank you! , I hope you can check it. 

Note: as we spoke on facebook  will be great to have 2nd button support built in AMAL.

**Comment by AmitenTV** [comment] 2022-05-27 15:36
Hi Frederic , 
Any news ?¿ I need thbis 2nd Button please ! :D

**Comment by AmiDARK** [comment] 2022-05-28 19:22
This bug was reproduced on WinUAE but was slightly different.
The method =fire(1,2) always return -1.
I will investigate this to find why it does not works correctly.

**Comment by AmitenTV** [comment] 2022-06-01 15:32
Hello , I discover that in fact The method =fire(1,2) WORKS!!! only we need to select in Winuae CD32 Control PAD to work properly! with Regular Joystick dont work , you Rock Frederic!!!

**Comment by AmiDARK** [comment] 2022-06-01 17:15
Great. It is apparently due to the way WinUAE map the joypad configuration.
CD32 Controller is compliant with native db9 port working with $DFF016 register.
I close this ticket then.
Thank you.

**Closed as completed by AmiDARK** 2022-06-01 17:15 UTC
